### ISSUE TITLE
Support HTTP keep alive

### ISSUE THREAD

**Issue by bploetz** [songkick/transport#3]
https://github.com/songkick/transport/blob/master/lib/songkick/transport/base.rb#L43

It would be nice to give users the option to use HTTP keep alive (which should be the default, IMHO) or close connections after each request.

**Comment by dwo** [comment]
Hi @bploetz. Sorry for taking so long to reply.

For our needs, we are mostly talking to services running Unicorn which doesn't really do Keep-Alive as I understand it. That's why it was the default when we built Transport.

Would you still be interested in doing a pull request for this feature or should I close it?

**Comment by bploetz** [comment]
@dwo We ended up using something else, so you can feel free to close this.
